x_offset: -0.01
y_offset: 0.012
z_offset: 0.035
roll_offset: 0
pitch_offset: 0
yaw_offset: 0
hip_pitch_offset: -4.99999985454646
period_time: 700
dsp_ratio: 0.4
step_forward_back_ratio: 0.3
foot_height: 0.016
swing_right_left: 0.016
swing_top_down: 0.02
pelvis_offset: 1.999999984507266
arm_swing_gain: 0.3
balance_hip_roll_gain: 0.35
balance_knee_gain: 0.3
balance_ankle_roll_gain: 0.7
balance_ankle_pitch_gain: 0.9
p_gain: 0
i_gain: 0
d_gain: 0