x_offset: -0.04
y_offset: 0.034
z_offset: 0.06
roll_offset: 0
pitch_offset: 0
yaw_offset: 0
hip_pitch_offset: -12.00000033393042
period_time: 800
dsp_ratio: 0.4
step_forward_back_ratio: 0.28
foot_height: 0.02
swing_right_left: 0.026
swing_top_down: 0.022
pelvis_offset: 0
arm_swing_gain: 0.2
balance_hip_roll_gain: 0.35
balance_knee_gain: 0.3
balance_ankle_roll_gain: 0.7
balance_ankle_pitch_gain: 0.9
p_gain: 0
i_gain: 0
d_gain: 0