# time parameter

mov_time : 3.0		# movement time

# target pose [deg] for online_walking_module

tar_pose :
  r_hip_yaw   :   0.0
  r_hip_roll  :   0.0
  r_hip_pitch :    16.0
  r_knee      :   -36.5
  r_ank_pitch :   -18.0
  r_ank_roll  :   0.0
  l_hip_yaw   :   0.0
  l_hip_roll  :   0.0
  l_hip_pitch :   -16.0
  l_knee      :   36.5
  l_ank_pitch :   18.0
  l_ank_roll  :   0.0
