exhx5:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------


  # HEAD
  j_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_pan
    pid: {p: 50.0, i: 0.01, d: 0.1}

  j_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_tilt
    pid: {p: 10.0, i: 0.01, d: 0.1}

  j_camboard_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_camboard
    pid: {p: 10.0, i: 0.01, d: 0.1}


  j_pelvis_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_pelvis_l
    pid: {p: 50.0, i: 0.01, d: 1.0}



  j_thigh1_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_thigh1_l
    pid: {p: 50.0, i: 0.01, d: 1.0}



  j_thigh2_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_thigh2_l
    pid: {p: 50.0, i: 0.01, d: 1.0}



  j_tibia_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_tibia_l
    pid: {p: 50.0, i: 0.01, d: 1.0}



  j_ankle1_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_ankle1_l
    pid: {p: 50.0, i: 0.01, d: 1.0}



  j_ankle2_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_ankle2_l
    pid: {p: 50.0, i: 0.01, d: 1.0}



  j_pelvis_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_pelvis_r
    pid: {p: 50.0, i: 0.01, d: 1.0}



  j_thigh1_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_thigh1_r
    pid: {p: 50.0, i: 0.01, d: 1.0}



  j_thigh2_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_thigh2_r
    pid: {p: 50.0, i: 0.01, d: 1.0}



  j_tibia_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_tibia_r
    pid: {p: 50.0, i: 0.01, d: 1.0}



  j_ankle1_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_ankle1_r
    pid: {p: 50.0, i: 0.01, d: 1.0}



  j_ankle2_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_ankle2_r
    pid: {p: 50.0, i: 0.01, d: 1.0}
