exhx5:

  # Publish all joint states -----------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
  # Position Controllers ---------------------------------------

  # Left Leg ---------------------------------------------------

  l_hip_yaw_position:
    type: effort_controllers/JointPositionController
    joint: l_hip_yaw
    pid: {p: 100.0, i: 0.0, d: 0.0}

  l_hip_roll_position:
    type: effort_controllers/JointPositionController
    joint: l_hip_roll
    pid: {p: 100.0, i: 1.0, d: 0.0}

  l_hip_pitch_position:
    type: effort_controllers/JointPositionController
    joint: l_hip_pitch
    pid: {p: 100.0, i: 0.0, d: 0.0}

  l_knee_position:
    type: effort_controllers/JointPositionController
    joint: l_knee
    pid: {p: 100.0, i: 0.0, d: 0.0}

  l_ank_roll_position:
    type: effort_controllers/JointPositionController
    joint: l_ank_roll
    pid: {p: 100.0, i: 0.00, d: 0.000}

  l_ank_pitch_position:
    type: effort_controllers/JointPositionController
    joint: l_ank_pitch
    pid: {p: 100.0, i: 0.00, d: 0.000}

  # Right Leg ---------------------------------------------------

  r_hip_yaw_position:
    type: effort_controllers/JointPositionController
    joint: r_hip_yaw
    pid: {p: 100.0, i: 0.0, d: 0.0}

  r_hip_roll_position:
    type: effort_controllers/JointPositionController
    joint: r_hip_roll
    pid: {p: 100.0, i: 0.0, d: 0.0}

  r_hip_pitch_position:
    type: effort_controllers/JointPositionController
    joint: r_hip_pitch
    pid: {p: 100.0, i: 0.0, d: 0.0}

  r_knee_position:
    type: effort_controllers/JointPositionController
    joint: r_knee
    pid: {p: 100.0, i: 0.0, d: 0.0}

  r_ank_roll_position:
    type: effort_controllers/JointPositionController
    joint: r_ank_roll
    pid: {p: 100.0, i: 0.0, d: 0.000}

  r_ank_pitch_position:
    type: effort_controllers/JointPositionController
    joint: r_ank_pitch
    pid: {p: 100.0, i: 0.0, d: 0.000}

  b_pitch_position:
    type: effort_controllers/JointPositionController
    joint: b_pitch
    pid: {p: 500.0, i: 0.0, d: 0.00}

  neck_pitch_position:
    type: effort_controllers/JointPositionController
    joint:  neck_pitch
    pid: {p: 100.0, i: 0.0, d: 0.0}

  head_tilt_position:
    type: effort_controllers/JointPositionController
    joint: head_tilt
    pid: {p: 10.0, i: 0.01, d: 0.0}

  head_pan_position:
    type: effort_controllers/JointPositionController
    joint: head_pan
    pid: {p: 10.0, i: 0.01, d: 0.0}  


