offset:
  l_ank_pitch: -0.00
  l_ank_roll: 0.00
  l_hip_pitch: 0.00
  l_hip_roll: -0.00
  l_hip_yaw: -0.00
  l_knee: -0.00
  r_ank_pitch: -0.0
  r_ank_roll: 0.00
  r_hip_pitch: -0.00
  r_hip_roll: 0.00
  r_hip_yaw: -0.00
  r_knee: 0.00
  head_pan: 0
  head_tilt: 0
  r_sho_pitch: 0.0
